export const ASSETS = {
  mascot: "./assets/mascot.svg",
  coin: "./assets/melody-coin.svg",
  puzzle: "./assets/puzzle-piece.svg",
  cover: "./assets/puzzle-cover.svg",
  artist: "./assets/artist-yoasobi.svg",
};

export const UI_TEXT = {
  levelPrefix: "Lv.",
  pieceUnit: "ピース",
  complete: "完成",
  notAcquired: "未入手",
  unreleasedMelody: "未解放メロディ",
  nowPlayingMystery: "未解放メロディを再生中",
  aria: {
    back: "戻る",
    candidateList: "ピース候補",
    preview: "少し聴く",
    listenLater: "あとで聴く",
    menu: "メニュー",
  },
  progressLabel: "レベル進行",
  templates: {
    remainingToComplete: ({ remaining, pieceUnit, complete }) => `あと${remaining}${pieceUnit}で${complete}！`,
    remainingShort: ({ remaining }) => `あと${remaining}`,
    playlistSubtitle: ({ dateLabel, locationLabel, connectedUsers }) => `${dateLabel}・${locationLabel}で${connectedUsers}人と音楽でつながりました`,
    encounterSummary: ({ newArtists, rareTracks, coinFallbacks }) => `新しいアーティスト${newArtists}組、レア曲${rareTracks}曲、コイン報酬${coinFallbacks}件`,
    previewUnlocked: ({ artistName, title }) => `${artistName} / ${title} を少し再生します`,
  },
  prompt: {
    guessTrack: "曲名を入力してください",
    wrongAnswer: "まだ違うようです。ヒントや試聴を使ってもう一度試してください。",
    previewLocked: "未解放メロディを少し再生します",
  },
  home: {
    todayMelody: "今日のメロディ",
    collection: "コレクション",
    trackPuzzles: "曲パズル",
    artists: "アーティスト",
    playlists: "プレイリスト",
    mission: "ミッション",
    recentTracks: "最近追加した曲",
    viewAll: "すべて見る",
    openDeliveredMelody: "届いたメロディを見る",
  },
  exchange: {
    title: "ピースを選ぼう",
    subtitle: "気になるピースを1つ選んでください",
    rewardLead: "この交換で手に入るもの",
    waitingSelection: "ピースを選んでください",
    confirmSelection: "このピースを選ぶ",
    preview: "少し聴く",
  },
  mystery: {
    title: "未解放メロディ",
    subtitle: "音とヒントで曲名を当てよう",
    later: "あとで",
    guess: "曲名を当てる",
    hint1: "1つ目のヒントを見る",
    hint2: "2つ目のヒントを見る",
    answer: "答えを見る",
    choices: "4択ヒント",
    youtube: "YouTubeで見て確認",
    youtubeReady: "確認すると曲名とアーティスト名を解放します",
    youtubeLocked: "広告視聴後に確認できます",
    confirm: "確認する",
    adShort: "CM",
  },
  puzzle: {
    title: "曲パズル",
    ownedPieces: "所持ピース",
    rewards: "完成報酬",
    coins: "メロディコイン",
    exp: "経験値",
    viewPieces: "ピース一覧を見る",
  },
  artist: {
    page: "アーティストページ",
    completedTracks: "曲パズル完成数",
    trackList: "曲パズル一覧",
    sortNewest: "新しい順",
    newTrack: "新しい曲が追加されました",
    collect: "集める",
  },
  playlist: {
    play: "再生",
    listenLater: "あとで",
    saved: "保存済み",
    todayEncounter: "今日の出会い",
    check: "確認",
  },
  modal: {
    hintTitle: "ヒントを解放",
    answerTitle: "答えを確認",
    hint1Body: "広告視聴で1つ目のヒントを解放できます。",
    hint2Body: "広告視聴で2つ目のヒントを解放できます。",
    answerBody: "広告視聴でYouTube確認を表示できます。",
    hint1Reward: "伏せ字の一部を表示",
    hint2Reward: "4択ヒントを表示",
    answerReward: "公式MV確認リンクを表示",
  },
};

export const seedData = {
  user: {
    id: "user_mia",
    name: "Mia",
    level: 1,
    levelProgress: 0,
    coins: 0,
  },
  collectionLabels: ["曲パズル", "アーティスト", "プレイリスト"],
  mission: {
    label: "デイリー",
    current: 0,
    target: 5,
  },
  tracks: {
    track_sunset_drive: {
      id: "track_sunset_drive",
      title: "Sunset Drive",
      artistId: "artist_niziu",
      artistName: "Niziu",
      pieceCount: 9,
      ownedPieces: [1, 2, 3, 4, 5, 6],
      rewardCoins: 100,
      rewardExp: 50,
      color: "sunset",
      isUnlocked: true,
      youtubeVideoId: "official-sunset-drive",
      thumbnailUrl: ASSETS.cover,
    },
    track_lemon: {
      id: "track_lemon",
      title: "Lemon",
      artistId: "artist_yonezu",
      artistName: "米津玄師",
      pieceCount: 9,
      ownedPieces: [],
      rewardCoins: 100,
      rewardExp: 50,
      color: "violet",
      isUnlocked: false,
      youtubeVideoId: "official-lemon",
      thumbnailUrl: ASSETS.cover,
      titleMasks: ["L??o?", "Le?o?", "Le?on"],
      choices: ["恋愛", "夏", "夜", "ドラマ"],
      tone: "やさしい余韻",
    },
    track_yoru: {
      id: "track_yoru",
      title: "夜に駆ける",
      artistId: "artist_yoasobi",
      artistName: "YOASOBI",
      pieceCount: 9,
      ownedPieces: [1, 2, 3, 4],
      rewardCoins: 100,
      rewardExp: 50,
      color: "berry",
      isUnlocked: false,
      youtubeVideoId: "official-yoru",
      thumbnailUrl: ASSETS.cover,
      titleMasks: ["?に駆ける", "夜に?ける", "夜に駆?る"],
      choices: ["夜", "疾走感", "小説", "出会い"],
      tone: "夜に聴きたい",
    },
    track_show: {
      id: "track_show",
      title: "唱",
      artistId: "artist_ado",
      artistName: "Ado",
      pieceCount: 9,
      ownedPieces: [1, 2, 3, 4, 5, 6, 7, 8],
      rewardCoins: 100,
      rewardExp: 50,
      color: "magic",
      isUnlocked: true,
      youtubeVideoId: "official-show",
      thumbnailUrl: ASSETS.cover,
    },
    track_kaiju: {
      id: "track_kaiju",
      title: "怪獣の花唄",
      artistId: "artist_vaundy",
      artistName: "Vaundy",
      pieceCount: 9,
      ownedPieces: [1, 2, 3, 4, 5, 6, 7],
      rewardCoins: 100,
      rewardExp: 50,
      color: "sunset",
      isUnlocked: true,
      youtubeVideoId: "official-kaiju",
      thumbnailUrl: ASSETS.cover,
    },
    track_anytime: {
      id: "track_anytime",
      title: "Anytime Anywhere",
      artistId: "artist_milet",
      artistName: "milet",
      pieceCount: 9,
      ownedPieces: [],
      rewardCoins: 100,
      rewardExp: 50,
      color: "violet",
      isUnlocked: false,
      youtubeVideoId: "official-anytime",
      thumbnailUrl: ASSETS.cover,
      titleMasks: ["A?ytime A?ywhere", "Anytime A?ywhere", "Anytime Anywher?"],
      choices: ["透明感", "旅", "祈り", "エンディング"],
      tone: "透明感",
    },
    track_blueberry: {
      id: "track_blueberry",
      title: "ブルーベリー",
      artistId: "artist_macaroni",
      artistName: "マカロニえんぴつ",
      pieceCount: 9,
      ownedPieces: [1, 2, 3, 4],
      rewardCoins: 100,
      rewardExp: 50,
      color: "berry",
      isUnlocked: true,
      youtubeVideoId: "official-blueberry",
      thumbnailUrl: ASSETS.cover,
    },
    track_magic_hour: {
      id: "track_magic_hour",
      title: "Magic Hour",
      artistId: "artist_higedan",
      artistName: "Official髭男dism",
      pieceCount: 9,
      ownedPieces: [1, 2, 3, 4, 5, 6, 7, 8],
      rewardCoins: 100,
      rewardExp: 50,
      color: "magic",
      isUnlocked: true,
      youtubeVideoId: "official-magic-hour",
      thumbnailUrl: ASSETS.cover,
    },
    track_halzion: {
      id: "track_halzion",
      title: "ハルジオン",
      artistId: "artist_yoasobi",
      artistName: "YOASOBI",
      pieceCount: 9,
      ownedPieces: [1, 2, 3, 4, 5, 6, 7],
      rewardCoins: 100,
      rewardExp: 50,
      color: "violet",
      isUnlocked: true,
      youtubeVideoId: "official-halzion",
      thumbnailUrl: ASSETS.cover,
    },
  },
  artists: {
    artist_yoasobi: {
      id: "artist_yoasobi",
      name: "YOASOBI",
      completedTrackPuzzles: 12,
      totalTrackPuzzles: 18,
      artistPuzzleProgress: 60,
      featuredTrackIds: ["track_yoru", "track_halzion"],
    },
  },
  encounters: {
    encounter_today_001: {
      id: "encounter_today_001",
      locationLabel: "大学",
      connectedUsers: 12,
      summary: {
        newArtists: 3,
        rareTracks: 1,
        coinFallbacks: 2,
      },
      rewardCoins: 50,
      expiresInSeconds: 45,
      candidates: [
        { trackId: "track_lemon", sourceSlot: "推し曲枠", pieceNumber: 1, rarity: "★★★★★" },
        { trackId: "track_yoru", sourceSlot: "発見枠", pieceNumber: 5, rarity: "★★★★★" },
        { trackId: "track_show", sourceSlot: "解放済み", pieceNumber: 9, rarity: "★★★★★" },
        { trackId: "track_kaiju", sourceSlot: "レア枠", pieceNumber: 8, rarity: "★★★★★" },
        { trackId: "track_anytime", sourceSlot: "イベント", pieceNumber: 1, rarity: "★★★★★" },
      ],
    },
  },
  dailyPlaylist: {
    id: "playlist_today",
    encounterId: "encounter_today_001",
    dateLabel: "2026年6月4日",
    title: "今日のメロディ",
    trackIds: ["track_sunset_drive", "track_blueberry", "track_magic_hour", "track_halzion"],
  },
};

export function initialAppState() {
  return {
    activeScreen: "home",
    coins: 0,
    activeEncounterId: "encounter_today_001",
    selectedTrackId: "track_lemon",
    selectedCandidateIndex: -1,
    selectedAdKind: null,
    unlockedTrackIds: Object.values(seedData.tracks).filter((track) => track.isUnlocked).map((track) => track.id),
    hintLevels: {},
    answerReadyTrackIds: [],
    collectedPieces: Object.fromEntries(
      Object.values(seedData.tracks).map((track) => [track.id, [...track.ownedPieces]]),
    ),
    listenLaterTrackIds: [],
    recentlyAddedTrackIds: ["track_sunset_drive", "track_blueberry", "track_magic_hour"],
    toast: null,
  };
}

export function formatNumber(value) {
  return new Intl.NumberFormat("ja-JP").format(value);
}

export function maskForTrack(track, hintLevel) {
  if (track.isUnlocked || !track.titleMasks) return `${track.artistName} / ${track.title}`;
  const titleMask = track.titleMasks[Math.min(hintLevel, track.titleMasks.length - 1)];
  return `${track.artistName} / ${titleMask}`;
}
